- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git-core
    - libtool
    - automake
    - autoconf
    - autoconf-archive
    - pkg-config
    - git
    - curl
    - build-essential
  tags: couchdb
