# installTwitterHarvestingInstance.yml
# deploy twiiter harvesting instacnces by using ancible playbook.
# ansible-playbook -i melbournehavesthosts DeployTwitterHarvestingInstance.yml --private-key Nectar_key --extra-vars="isFirstRun=true"
---
- hosts: tweetharv  # hosts address of tweet harvesting instances.
  sudo: True  # with sudo privilege
  remote_user: ubuntu  # ubuntu
  vars: #some variables, indicating the version of softwares which we are going to use and where we should download them
    nodejs_version: 0.10.28
    nodejs_install_dir: /home/ubuntu/nodejs

    rebar_version: 2.5.1   
    rebar_install_dir: /mnt/myVolume

    couchdb_version: developer-preview-2.0
    couchdb_install_dir: /mnt/myVolume

    download_url: http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    download_folder: /mnt/myVolume

    java_name: "{{download_folder}}/jdk1.8.0_05"
    java_archive: "{{download_folder}}/jdk-8u5-linux-x64.tar.gz"

  tasks:
    #format the volume on VM
    - name: formatting out attached volume
      shell: 'sudo mkfs.ext4 /dev/vdc'
      when: (isFirstRun == 'true')
    #create new folder /mnt/myVolume
    - name: create folder /mnt/myVolume
      shell: 'sudo mkdir /mnt/myVolume'
      when: (isFirstRun == 'true')
    #mount our volume to the location /mnt/myVolume
    - name: mount
      shell: 'sudo mount /dev/vdc /mnt/myVolume' 
      when: (isFirstRun == 'true')

    #update source list on target mechines.
    - name: Run "apt-get update" to update the source list
      apt: update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    #install java
    - include: tasks/installjava.yml
    #install couchDB
    - include: tasks/installaptcouchdb.yml
    #install python
    #- include: tasks/installpython.yml
    #install some important dependencies.
    - include: tasks/installdeps.yml

    #install pip
    - name: install pip
      shell: 'sudo apt-get install python-pip'
      sudo: 'yes'

    #install tweepy
    - name: install tweepy
      shell: 'sudo pip install tweepy'
      sudo: 'yes'
    #download the source code of tweet harvesting program from the github repositiory.
    #- name: download source codes from git
     # git: repo=https://github.com/wangsure/shnewla.git dest=/mnt/thnew
    #update all the packages.
    - name: Update all packages to the latest version
      apt: upgrade=dist
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
   # - name: Run program script
   #   script: /mnt/thnew/start.sh jobs_instance.txt



