# installCouchDB.yml
# deploy CouchDB instacnces by using ancible playbook.
---
- hosts: tweetcouchdb  # hosts address of CouchDB instances
  sudo: True # with sudo privilege
  remote_user: ubuntu  #username: ubuntu 
  vars: #some variables, incicating the version of softwares which we are going to use
    nodejs_version: 0.10.28
    nodejs_install_dir: /mnt/myVolume

    rebar_version: 2.5.1
    rebar_install_dir: /mnt/myVolume

    couchdb_version: developer-preview-2.0
    couchdb_install_dir: /mnt/myVolume

  tasks:
    #- name: create new folder /mnt/myVolume
    #  shell: 'mkdir /mnt/myVolume'
    #format the volume on VM
    #- name: formatting our attached volume
    #  shell: 'sudo mkfs.ext4 /dev/vdc'
    #mount our volunme to the location /mnt
    #- name: mount
    #  shell: 'sudo mount /dev/vdc /mnt/myVolume'
    #enter to the /mnt/myVolume directory
    #- name: enter folder
    #  shell: 'cd /mnt/myVolume'
    #update the source list on target machine
    - name: Run "apt-get update" to update the source list
      apt: update_cache=yes
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    #install java
    - include: tasks/installjava.yml
    #install some important dependencies.
    - include: tasks/installdeps.yml
    #install  couchDB.
    - include: tasks/installaptcouchdb.yml
    #install python
    #- include: tasks/installpython.yml
    #update all the packages.
    - name: Update all packages to the latest version
      apt: upgrade=dist
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


